notifications:
  email: false
  slack:
    rooms:
      secure: S3xDhrrLgQ1DSBgc42M9wkJzmqYlv/FSeKhcOxDVspy8s/N2N4z4JCGpuX3RYIPEHNIaao9gTvQJ5Ddoq5hCppXncyKsmH4NvDVQ1JdjTRk5KXp6SC0mJvJ7Vh4pKhcpJu87sh9dZs9Io6VqqG/bGpcjt9SFgVz/n24DPKgeREa351GorhncFmnG3ZtItHGe5a7n5V9sM3g5uLUf0ELPew6iPvkyx5xNvyMfMrgcJDbXKHQR6S5xvp7Pw/GkXGVR7d1nQElKMsDOlEiui+l2ctRFo0ZnNGoVzvLGKygkw717Q6k215Gq7x/eZI5//Kidwxra0ks7NYhYhzayRiy+pJ2ZYH3N8c5KL6xbVzyNn8LpP733Ra48oJZK+yjk77TAIkwvBsoH0p1Hc1fi12fdgrhACHa48zy/ILMcnGILfX5BOjVwpPy2dUbiKQHmClrq4Fe+t9vK11wqEjJr/bm2WfmbqEudWn3Kb1Vpk5ZohNZuhXcqJ/PdT9ns9ac8jNHxP3mAiCulOQbRNFq95ZjYQuMscKzlw18WUNyfi/5hsMCKgi78Kbg5Bzia1SieF0w+uo3qHDNIEPiuQevrSc0zGLUaPn+G4O08tx75Gxjg23/leBvn36qv2rXG1+RjL7saj00S2sTSKEB9rXWf8unE19Rh2gXDg4Asxyr63nOLBBI=
    on_success: always
    on_failure: always

stages:
- name: BUILD
- name: TEST
- name: DEPLOY
- name: ANDROID
- name: IOS

jobs:
  include:

  - stage: BUILD
    os: linux
    language: node_js
    node_js:
    - '8'
    services:
    - docker
    before_script:
    - export -f travis_fold
    script:
    - bash .travis.build.sh

  - stage: TEST
    os: linux  
    language: node_js
    node_js:
    - '8'
    services:
    - docker
    addons:
      code_climate:
        repo_token: 19d3ef0c5e4541c913514b7a3a3825829e5e354f08dc39fd2c03b7898958d597
    install:
    - pip install --user awscli
    - npm install -g codeclimate-test-reporter
    before_script:
    - export -f travis_fold
    script:
    - bash .travis.test.sh

  - stage: DEPLOY
    os: linux  
    language: node_js
    node_js:
    - '8'
    services:
    - docker
    install: true
    before_script:
    - export -f travis_fold 
    script:
    - bash .travis.deploy.sh

  - stage: ANDROID
    os: linux
    language: android
    jdk: oraclejdk8
    android:
      components:
      - tools
      - tools  # Include again to work around travis not using the latest, see: https://github.com/travis-ci/travis-ci/issues/6193
      - platform-tools
      - build-tools-27.0.3
      - android-27
    licenses:
      - '.+'
    before_install:
    # NVM
    - nvm install 8
    # AndroidDK Licence Mangager
    - yes | sdkmanager "platforms;android-27"
    # Yarn
    - npm install -g yarn
    # AWS cli
    - pip install --user awscli
    # Fastlane
    - gem install fastlane -v '~> 2.137.0'
    # Quasar cli
    - npm install -g @quasar/cli  
    install:
    - yarn
    before_script:
    - export -f travis_fold    
    script:
    - bash .travis.android.sh

  - stage: IOS
    os: osx
    language: objective-c
    osx_image: xcode10.1
    before_install:
    # NVM
    - nvm install 8
    # Yarn
    - npm install -g yarn
    # AWS cli
    - brew install awscli
    # Ios deploy
    - npm install -g ios-deploy --unsafe-perm=true
    # Quasar cli
    - npm install -g @quasar/cli  
    install:
    - yarn
    before_script:
    - export -f travis_fold   
    script:
    - bash .travis.ios.sh
