notifications:
  email: false
  slack:
    rooms:
      secure: S3xDhrrLgQ1DSBgc42M9wkJzmqYlv/FSeKhcOxDVspy8s/N2N4z4JCGpuX3RYIPEHNIaao9gTvQJ5Ddoq5hCppXncyKsmH4NvDVQ1JdjTRk5KXp6SC0mJvJ7Vh4pKhcpJu87sh9dZs9Io6VqqG/bGpcjt9SFgVz/n24DPKgeREa351GorhncFmnG3ZtItHGe5a7n5V9sM3g5uLUf0ELPew6iPvkyx5xNvyMfMrgcJDbXKHQR6S5xvp7Pw/GkXGVR7d1nQElKMsDOlEiui+l2ctRFo0ZnNGoVzvLGKygkw717Q6k215Gq7x/eZI5//Kidwxra0ks7NYhYhzayRiy+pJ2ZYH3N8c5KL6xbVzyNn8LpP733Ra48oJZK+yjk77TAIkwvBsoH0p1Hc1fi12fdgrhACHa48zy/ILMcnGILfX5BOjVwpPy2dUbiKQHmClrq4Fe+t9vK11wqEjJr/bm2WfmbqEudWn3Kb1Vpk5ZohNZuhXcqJ/PdT9ns9ac8jNHxP3mAiCulOQbRNFq95ZjYQuMscKzlw18WUNyfi/5hsMCKgi78Kbg5Bzia1SieF0w+uo3qHDNIEPiuQevrSc0zGLUaPn+G4O08tx75Gxjg23/leBvn36qv2rXG1+RjL7saj00S2sTSKEB9rXWf8unE19Rh2gXDg4Asxyr63nOLBBI=
    on_success: always
    on_failure: always

# stage: TEST 
# Must be declared here to enable build matrix
language: node_js
node_js:
- '8'    
env:
  matrix:
  - TEST_SCOPE=api TEST_BROWSER=none
  - TEST_SCOPE=account TEST_BROWSER=chromium
  - TEST_SCOPE=account TEST_BROWSER=firefox
  - TEST_SCOPE=authentication TEST_BROWSER=chromium
  - TEST_SCOPE=authentication TEST_BROWSER=firefox
before_install:
- pip install --user awscli
script:
- bash .travis.test.sh $TEST_SCOPE

stages:
- name: BUILD
  if: commit_message !~ /(skip[ _-]build)/
- name: TEST
  if: commit_message !~ /(skip[ _-]test)/
- name: DEPLOY
  if: commit_message !~ /(skip[ _-]deploy)/
- name: ANDROID
  if: commit_message !~ /(skip[ _-]android)/
- name: IOS
  if: commit_message !~ /(skip[ _-]ios)/

jobs:
  include:

  - stage: BUILD
    os: linux
    language: node_js
    node_js:
    - '8'
    services:
    - docker
    env:
    - TEST_SCOPE=none TEST_BROWSER=none
    script:
    - bash .travis.build.sh

  - stage: DEPLOY
    os: linux  
    language: node_js
    node_js:
    - '8'
    services:
    - docker
    env:
    - TEST_SCOPE=none TEST_BROWSER=none
    install: true
    script:
    - bash .travis.deploy.sh

  - stage: ANDROID
    os: linux
    language: android
    jdk: oraclejdk8
    android:
      components:
      - tools
      - tools  # Include again to work around travis not using the latest, see: https://github.com/travis-ci/travis-ci/issues/6193
      - platform-tools
      - build-tools-28.0.3
      - android-28
    licenses:
      - '.+'
    env:
    - TEST_SCOPE=none TEST_BROWSER=none
    before_install:
    # NVM
    - nvm install 8
    # AndroidDK Licence Mangager
    - yes | sdkmanager "platforms;android-28"
    # Yarn
    - npm install -g yarn
    # AWS cli
    - pip install --user awscli
    # Fastlane
    - gem install fastlane -v '~> 2.137.0'
    # Quasar cli
    - npm install -g @quasar/cli  
    install:
    - yarn
    before_script:
    - export -f travis_fold    
    script:
    - bash .travis.android.sh

  - stage: IOS
    os: osx
    language: objective-c
    osx_image: xcode10.1
    env:
    - TEST_SCOPE=none TEST_BROWSER=none
    before_install:
    # NVM
    - nvm install 8
    # Yarn
    - npm install -g yarn
    # AWS cli
    - brew install awscli
    # Ios deploy
    - npm install -g ios-deploy --unsafe-perm=true
    # Quasar cli
    - npm install -g @quasar/cli  
    install:
    - yarn
    before_script:
    - export -f travis_fold   
    script:
    - travis_wait 30 bash .travis.ios.sh
