version: '3.3'

services:
  app:
    image: kalisio/${APP}:${VERSION_TAG}
    env_file:
      - ../.env
    networks:
      - app-network

networks:
  app-network:
    external:
      name: ${DOCKER_NETWORK}
