version: '3.3'

services:
  testcafe:
    image: kalisio/testcafe:1.3.3
    depends_on:
      - mongodb
      - app
    environment:
      - GOOGLE_USER
      - GOOGLE_PASSWORD
      - GITHUB_USER
      - GITHUB_PASSWORD
      - NODE_ENV=production
      - DB_URL=mongodb://mongodb:27017/${APP}
      - APP_URL=app:${PORT}
      volumes:
        - ../test:/tests
        - ../screenshots:/screenshots
      command: firefox:headless /tests/*.test.js -S -s /screenshots -f $FIXTURE
      networks:
        - app-network

networks:
  app-network:
    external:
      name: ${DOCKER_NETWORK}