version: '3.3'

services:
  testcafe:
    image: kalisio/testcafe:${TESTCAFE_TAG}
    depends_on:
      - mongodb
      - app
    environment:
      - NODE_ENV=production
      - DB_URL=mongodb://mongodb:27017/${APP}
      - APP_URL=app:${PORT}
    volumes:
      - ../test:/tests
      - ../screenshots:/screenshots
    command: ${TEST_BROWSER}:headless /tests/*.test.js -S -s /screenshots --speed ${TEST_SPEED:-0.5} -f $FIXTURE 
    networks:
      - app-network
      
networks:
  app-network:
    external:
      name: ${DOCKER_NETWORK}